// Types para la validación
export const VALIDAR_FORMULARIO = 'VALIDAR_FORMULARIO';
export const VALIDAR_FORMULARIO_EXITO = 'VALIDAR_FORMULARIO_EXITO';
export const VALIDAR_FORMULARIO_ERROR = 'VALIDAR_FORMULARIO_ERROR';

// Types para agregar producto
export const AGREGAR_PRODUCTO = 'AGREGAR_PRODUCTO';
export const AGREGAR_PRODUCTO_EXITO = 'AGREGAR_PRODUCTO_EXITO';
export const AGREGAR_PRODUCTO_ERROR = 'AGREGAR_PRODUCTO_ERROR';

//Types para mostrar los datos
export const DESCARGA_PRODUCTOS_INICIADA = 'COMENZAR_DESCARGA_PRODUCTOS';
export const DESCARGA_PRODUCTOS_EXITOSA = 'COMENZAR_DESCARGA_PRODUCTOS_EXITOSA';
export const DESCARGA_PRODUCTOS_ERROR = 'COMENZAR_DESCARGA_PRODUCTOS_ERROR';

//Types para borrar un registro
export const PRODUCTO_ELIMINAR_OBTENER = 'PRODUCTO_ELIMINAR_OBTENER';
export const PRODUCTO_ELIMINAR_EXITO = 'PRODUCTO_ELIMINAR_EXITO';
export const PRODUCTO_ELIMINAR_ERROR = 'PRODUCTO_ELIMINAR_ERROR';

//Types para edición
export const PRODUCTO_EDITAR_OBTENER = 'PRODUCTO_EDITAR_OBTENER';
export const PRODUCTO_EDITAR_EXITO = 'PRODUCTO_EDITAR_EXITO';
export const PRODUCTO_EDITAR_ERROR = 'PRODUCTO_EDITAR_ERROR';
